title: "GET :: Genomes Environments Traits Conference"
author: "GET :: Genomes Environments Traits Conference"
email: info@getconference.org
description: > # this means to ignore newlines until "show_excerpts:"
  For the past six years, this event has explored the frontiers of
  understanding about human biology. It serves as an annual forum to debate
  the technical, commercial, and societal impacts of advances in our
  ability to measure and understand people and their traits.

  The GET Conference is produced by PersonalGenomes.org, a 501(c)(3)
  charitable organization based in the United States whose mission is to
  make a wide spectrum of human biological information accessible and
  actionable to increase biological literacy and improve human health.
  We support groundbreaking initiatives including the Global Network of
  Personal Genome Projects, Open Humans and the GET Conference.
# baseurl: "/pgpconference" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Jekyll SEO Tag Settings
logo: /assets/images/get-fav-logo-204x230.png
social:
  - https://twitter.com/attendGET
  # - https://facebook.com/PersonalGenomesOrg
  - https://www.linkedin.com/company/personalgenomes-org
  - https://www.youtube.com/user/PersonalGenomesOrg

twitter:
  username: attendGET
  card: summary

twitter_username: attendGET
google_analytics: UA-145673922-2
port: 5000

show_excerpts: false # set to true to show excerpts on the homepage
excerpt_seperator: "<!--more-->"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # See https://github.com/jekyll/minima/blob/master/_config.yml for a full list
  social_links:
    twitter: attendGET
    # github:  jekyll
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown
theme: minima

plugins:
  - github-pages
  - jekyll-admin
  - jekyll-feed
  - jekyll-figure
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings


exclude:
  - Gemfile
  - Gemfile.lock
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/
  # - accessibility
  - docs
  - node_modules
  - README.md
  - ref
  - scratch
  - ["docs", "ref", "scratch"]

excerpt_separator: "<!--more-->"
sass:
  style: expanded
  sourcemap: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

collections:
  agenda2012:
    output: false
  awards2016:
    output: false
  awards-presenters2010:
    output: false
  breakout-leaders2010:
    output: false
  discussion-leaders2010:
    output: false
  discussion-leaders2012:
    output: false
  discussion-leaders2013:
    output: false
  expos2016:
    output: false
  judges2016:
    output: false
  labs2010:
    output: false
  labs2011:
    output: false
  labs2012:
    output: false
  labs2013:
    output: false
  labs2014:
    output: false
  labs2016:
    output: false
  media-partners2016:
    output: false
  moderators2010:
    output: false
  organizers2014:
    output: false
  organizers2015:
    output: false
  organizers2016:
    output: false
  past-conferences2016:
    output: false
  prototypes2010:
    output: false
  speakers2010:
    output: false
  speakers2011:
    output: false
  speakers2012:
    output: false
  speakers2013:
    output: false
  speakers2014:
    output: false
  speakers2015:
    output: false
  speakers2016:
    output: false
  sponsors2010:
    output: false
  sponsors2011:
    output: false
  sponsors2012:
    output: false
  sponsors2013:
    output: false
  sponsors2014:
    output: false
  sponsors2015:
    output: false
  sponsors2016:
    output: false
